import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
import { createPbrDecalMaterial, enablePomDecalMaterial, updatePomDecalMaterial } from './PomDecalMaterial.js';
import { preparePomReliefMaps, getPomReliefBounds } from './PomReliefProfile.js';

const $ = id => document.getElementById(id);
const SIZE = 512, COUNT = SIZE * SIZE;
const ASSETS = Array.from({ length: 10 }, (_, i) => ({ id:`ref-${String(i+1).padStart(2,'0')}`, url:`./reference-pom-assets/ref-${String(i+1).padStart(2,'0')}.webp` }));
const state = window.__REFERENCE_POM_LAB__ = { ready:false, errors:[], selected:null, renderCount:0, size:SIZE, version:'reference-runtime-v1' };
const status = $('status');
function fail(error){const text=error instanceof Error?error.message:String(error);state.errors.push(text);state.ready=false;status.dataset.state='error';status.textContent='Ошибка: '+text;console.error(error);}
window.addEventListener('error',e=>fail(e.error||e.message));window.addEventListener('unhandledrejection',e=>fail(e.reason));

for(const a of ASSETS){const o=document.createElement('option');o.value=a.id;o.textContent=a.id.toUpperCase();$('decal').appendChild(o);}

const defaults={heightScale:.028,neutralLevel:.56,raiseScale:.55,sinkScale:1.35,wallSoftnessPx:1,minSteps:12,maxSteps:96,refinementSteps:6,maxUvOffset:.28,grazingFadeStart:.08,grazingFadeEnd:.22,jitterStrength:0,stableGradients:true};
const ids={heightScale:'height',neutralLevel:'neutralLevel',raiseScale:'raiseScale',sinkScale:'sinkScale',wallSoftnessPx:'wallSoftnessPx',minSteps:'minSteps',maxSteps:'maxSteps',refinementSteps:'refine',maxUvOffset:'maxUvOffset',grazingFadeStart:'grazingFadeStart',grazingFadeEnd:'grazingFadeEnd',jitterStrength:'jitterStrength'};
const outIds={heightScale:'heightOut',neutralLevel:'neutralLevelOut',raiseScale:'raiseScaleOut',sinkScale:'sinkScaleOut',wallSoftnessPx:'wallSoftnessPxOut',minSteps:'minOut',maxSteps:'maxOut',refinementSteps:'refineOut',maxUvOffset:'maxUvOffsetOut',grazingFadeStart:'grazingFadeStartOut',grazingFadeEnd:'grazingFadeEndOut',jitterStrength:'jitterStrengthOut'};
function readParams(){const p=Object.fromEntries(Object.entries(ids).map(([k,id])=>[k,Number($(id).value)]));p.stableGradients=$('stableGradients').checked;p.minSteps=Math.min(p.minSteps,p.maxSteps);p.grazingFadeEnd=Math.max(p.grazingFadeStart+.001,p.grazingFadeEnd);return p;}
function assignParams(p){for(const[k,v]of Object.entries(p)){if(ids[k])$(ids[k]).value=String(v);if(k==='stableGradients')$('stableGradients').checked=!!v;}}
function updateOutputs(p){for(const[k,id]of Object.entries(outIds)){const n=p[k];$(id).textContent=['minSteps','maxSteps','refinementSteps'].includes(k)?String(Math.round(n)):k==='heightScale'?n.toFixed(3):n.toFixed(2);}}

function loadImage(url){return new Promise((resolve,reject)=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Не удалось загрузить '+url));im.src=url+'?v=2';});}
function floodBlackBackground(data,w,h){const bg=new Uint8Array(w*h),q=new Int32Array(w*h),cand=new Uint8Array(w*h);let qs=0,qe=0;for(let i=0;i<w*h;i++){const o=i*4,r=data[o],g=data[o+1],b=data[o+2],a=data[o+3];cand[i]=(a<12||(Math.max(r,g,b)<18&&Math.max(r,g,b)-Math.min(r,g,b)<12))?1:0;}const add=i=>{if(cand[i]&&!bg[i]){bg[i]=1;q[qe++]=i;}};for(let x=0;x<w;x++){add(x);add((h-1)*w+x);}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1);}while(qs<qe){const i=q[qs++],x=i%w,y=(i/w)|0;if(x) add(i-1);if(x<w-1)add(i+1);if(y)add(i-w);if(y<h-1)add(i+w);}return bg;}
function reconstruct(image){
  const c=document.createElement('canvas');c.width=c.height=SIZE;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.clearRect(0,0,SIZE,SIZE);const scale=Math.min(480/image.naturalWidth,480/image.naturalHeight);const w=Math.max(1,Math.round(image.naturalWidth*scale)),h=Math.max(1,Math.round(image.naturalHeight*scale)),x=((SIZE-w)/2)|0,y=((SIZE-h)/2)|0;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(image,x,y,w,h);const id=ctx.getImageData(0,0,SIZE,SIZE),rgba=new Uint8Array(id.data),alpha=new Uint8Array(COUNT),height=new Uint8Array(COUNT);let transparent=0;for(let i=0;i<COUNT;i++)if(rgba[i*4+3]<250)transparent++;const bg=transparent<COUNT*.01?floodBlackBackground(rgba,SIZE,SIZE):null;
  for(let i=0;i<COUNT;i++){const o=i*4,r=rgba[o],g=rgba[o+1],b=rgba[o+2];let a=rgba[o+3];if(bg&&bg[i])a=0;alpha[i]=a;if(a<8){height[i]=Math.round(defaults.neutralLevel*255);rgba[o+3]=0;continue;}const l=(.2126*r+.7152*g+.0722*b)/255;const max=Math.max(r,g,b),min=Math.min(r,g,b);const chroma=(max-min)/255;let hh=.08+.88*Math.pow(l,.82);if(r>g*1.25&&r>b*1.4&&r>120)hh=Math.max(hh,.68);if(l<.16)hh=Math.min(hh,.22);hh+=Math.min(.04,chroma*.06);height[i]=Math.round(THREE.MathUtils.clamp(hh,0,1)*255);rgba[o+3]=a;}
  return {rgba,alpha,height,sourceSize:[image.naturalWidth,image.naturalHeight],content:[w,h],offset:[x,y]};
}
function rgbaFrom1(src){const b=new Uint8Array(COUNT*4);for(let i=0;i<COUNT;i++){const v=src[i],o=i*4;b[o]=b[o+1]=b[o+2]=v;b[o+3]=255;}return b;}
function rgbaFrom3(src){const b=new Uint8Array(COUNT*4);for(let i=0;i<COUNT;i++){const o=i*4,j=i*3;b[o]=src[j];b[o+1]=src[j+1];b[o+2]=src[j+2];b[o+3]=255;}return b;}
function texture(bytes,srgb=false,type=THREE.UnsignedByteType){const t=new THREE.DataTexture(bytes,SIZE,SIZE,THREE.RGBAFormat,type);t.colorSpace=srgb?THREE.SRGBColorSpace:THREE.NoColorSpace;t.flipY=false;t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=true;t.needsUpdate=true;return t;}
function solid(r,g,b){const t=new THREE.DataTexture(new Uint8Array([r,g,b,255]),1,1,THREE.RGBAFormat);t.needsUpdate=true;return t;}

const renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x131923);scene.add(new THREE.HemisphereLight(0xffffff,0x728091,1.15));const key=new THREE.DirectionalLight(0xffffff,2.7);scene.add(key,key.target);const camera=new THREE.PerspectiveCamera(42,1,.05,100),controls=new OrbitControls(camera,$('canvas'));controls.enableDamping=true;controls.minDistance=2.1;controls.maxDistance=15;const geometry=new THREE.PlaneGeometry(2.8,2.8);geometry.setAttribute('uv1',geometry.getAttribute('uv').clone());const mesh=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color:0x333333}));scene.add(mesh);const white=solid(205,208,214),black=solid(0,0,0),orm=solid(230,185,18);
let width=1,screenHeight=1,current=null,flat=null,pom=null,debugHeight=null,debugNormal=null,debugAlpha=null,lastFieldKey='',pending=0,loadingToken=0;
function disposeMaterial(m){if(m&&m.dispose)m.dispose();}
function disposeMaps(m){if(!m)return;for(const t of Object.values(m))if(t?.dispose)t.dispose();}
function makePbr(isPom){const m=createPbrDecalMaterial({tint:'#ffffff'},{baseColor:current.maps.base,normal:current.maps.normal,orm,emissive:black});m.transparent=true;m.opacity=1;m.side=THREE.DoubleSide;m.depthWrite=true;m.polygonOffset=false;m.roughness=.82;m.metalness=.1;m.aoMapIntensity=.55;m.normalScale.set(1,1);if(isPom)enablePomDecalMaterial(m,{heightMap:current.maps.height,...defaults});return m;}
function rebuildMaterials(){disposeMaterial(flat);disposeMaterial(pom);disposeMaterial(debugHeight);disposeMaterial(debugNormal);disposeMaterial(debugAlpha);flat=makePbr(false);pom=makePbr(true);debugHeight=new THREE.MeshBasicMaterial({map:current.maps.height,side:THREE.DoubleSide,toneMapped:false,transparent:true,alphaMap:current.maps.alpha,alphaTest:.05});debugNormal=new THREE.MeshBasicMaterial({map:current.maps.normal,side:THREE.DoubleSide,toneMapped:false,transparent:true,alphaMap:current.maps.alpha,alphaTest:.05});debugAlpha=new THREE.MeshBasicMaterial({map:current.maps.alpha,side:THREE.DoubleSide,toneMapped:false});lastFieldKey='';parameters();displayMode();}
async function selectAsset(id){const token=++loadingToken;status.dataset.state='';status.textContent='Загрузка '+id.toUpperCase()+' и реконструкция карт 512²…';const asset=ASSETS.find(a=>a.id===id);const image=await loadImage(asset.url);if(token!==loadingToken)return;const src=reconstruct(image);disposeMaps(current?.maps);const maps={base:texture(src.rgba,true),alpha:texture(rgbaFrom1(src.alpha)),normal:texture(new Uint8Array(COUNT*4)),height:null};const heightData=new Uint16Array(COUNT*4);maps.height=new THREE.DataTexture(heightData,SIZE,SIZE,THREE.RGBAFormat,THREE.HalfFloatType);maps.height.colorSpace=THREE.NoColorSpace;maps.height.flipY=false;maps.height.wrapS=maps.height.wrapT=THREE.ClampToEdgeWrapping;maps.height.minFilter=THREE.LinearMipmapLinearFilter;maps.height.magFilter=THREE.LinearFilter;maps.height.generateMipmaps=true;current={asset,src,maps,heightData};state.selected=id;$('selected').textContent=id.toUpperCase();rebuildMaterials();status.dataset.state='ready';status.textContent=`Готово · ${id.toUpperCase()} · source ${src.sourceSize[0]}×${src.sourceSize[1]} → runtime Base/Height/Normal/Alpha 512²`;state.ready=true;state.sourceSize=src.sourceSize;}
function parameters(){if(!current||!pom)return;const p=readParams(),key=JSON.stringify([p.heightScale,p.neutralLevel,p.raiseScale,p.sinkScale,p.wallSoftnessPx]);if(key!==lastFieldKey){const prepared=preparePomReliefMaps(current.src.height,SIZE,SIZE,p,current.src.alpha);for(let i=0;i<COUNT;i++){const h=THREE.DataUtils.toHalfFloat(prepared.heightField[i]),o=i*4;current.heightData[o]=current.heightData[o+1]=current.heightData[o+2]=h;current.heightData[o+3]=15360;}current.maps.height.needsUpdate=true;current.maps.normal.image.data=rgbaFrom3(prepared.normal);current.maps.normal.needsUpdate=true;lastFieldKey=key;state.fieldBuilds=(state.fieldBuilds||0)+1;}updatePomDecalMaterial(pom,p);updateOutputs(p);state.parameters=p;state.bounds=getPomReliefBounds(p);state.programKey=pom.customProgramCacheKey();$('shader').textContent='POM v4';$('range').textContent=`+${(state.bounds.top*p.heightScale).toFixed(4)} / ${(state.bounds.bottom*p.heightScale).toFixed(4)}`;}
function scheduleParameters(){cancelAnimationFrame(pending);pending=requestAnimationFrame(()=>{parameters();displayMode();});}
function displayMode(){if(!current||!flat||!pom)return;const mode=$('mode').value,cut=$('cutout').checked;for(const m of[flat,pom]){m.map=mode==='clay'?white:current.maps.base;m.alphaMap=cut?current.maps.alpha:null;m.alphaTest=cut?.35:0;m.transparent=cut;m.needsUpdate=true;}render();}
function resize(){const b=$('view').getBoundingClientRect();width=Math.max(2,Math.floor(b.width));screenHeight=Math.max(1,Math.floor(b.height));renderer.setSize(width,screenHeight,false);camera.aspect=Math.floor(width/2)/screenHeight;camera.updateProjectionMatrix();}
function cameraPreset(kind){const dist=Math.max(4.4,1.65/(Math.tan(THREE.MathUtils.degToRad(21))*camera.aspect));const dir=kind==='grazing'?new THREE.Vector3(.96,.06,.28):kind==='oblique'?new THREE.Vector3(.55,.17,1):new THREE.Vector3(0,0,1);camera.position.copy(dir.normalize().multiplyScalar(dist));controls.target.set(0,0,0);controls.update();}
function light(){const a=THREE.MathUtils.degToRad(Number($('az').value)),e=THREE.MathUtils.degToRad(Number($('el').value));key.position.set(Math.cos(e)*Math.sin(a)*5,Math.sin(e)*5,Math.cos(e)*Math.cos(a)*5);$('azOut').textContent=$('az').value+'°';$('elOut').textContent=$('el').value+'°';}
function render(){renderer.setScissorTest(true);const s=Math.floor(width/2),mode=$('mode').value;let left=flat,right=pom;if(mode==='height')left=right=debugHeight;else if(mode==='normal')left=right=debugNormal;else if(mode==='alpha')left=right=debugAlpha;mesh.material=left;renderer.setViewport(0,0,s,screenHeight);renderer.setScissor(0,0,s,screenHeight);renderer.render(scene,camera);mesh.material=right;renderer.setViewport(s,0,width-s,screenHeight);renderer.setScissor(s,0,width-s,screenHeight);renderer.render(scene,camera);renderer.setScissorTest(false);state.renderCount++;}
assignParams(defaults);new ResizeObserver(resize).observe($('view'));resize();cameraPreset('front');light();
for(const id of Object.values(ids))$(id).addEventListener('input',scheduleParameters);$('stableGradients').onchange=scheduleParameters;for(const id of['az','el'])$(id).addEventListener('input',()=>{light();render();});$('mode').onchange=displayMode;$('cutout').onchange=displayMode;$('decal').onchange=()=>selectAsset($('decal').value).catch(fail);for(const id of['front','oblique','grazing'])$(id).onclick=()=>{cameraPreset(id);render();};$('reset').onclick=()=>{assignParams(defaults);$('az').value='35';$('el').value='55';$('mode').value='pbr';$('cutout').checked=true;parameters();light();displayMode();cameraPreset('front');};
state.select=id=>{ $('decal').value=id; return selectAsset(id);};state.setParameters=p=>{assignParams(p);parameters();render();};state.cameraPreset=k=>{cameraPreset(k);render();};state.render=render;
let frames=0,t=performance.now();function frame(now){controls.update();render();frames++;if(now-t>=800){$('fps').textContent=String(Math.round(frames*1000/(now-t)));frames=0;t=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
selectAsset(ASSETS[0].id).catch(fail);
