import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
import { createPbrDecalMaterial, enablePomDecalMaterial, updatePomDecalMaterial } from './PomDecalMaterial.js';
import { preparePomReliefMaps } from './PomReliefProfile.js';
const $=id=>document.getElementById(id), status=$('status');
const state=window.__REFERENCE_POM_HD__={ready:false,source:null,renderCount:0,errors:[]};
const renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x131923);scene.add(new THREE.HemisphereLight(0xffffff,0x728091,1.1));const key=new THREE.DirectionalLight(0xffffff,2.7);scene.add(key,key.target);
const camera=new THREE.PerspectiveCamera(42,1,.05,100),controls=new OrbitControls(camera,$('canvas'));controls.enableDamping=true;controls.minDistance=1.4;controls.maxDistance=18;
const geometry=new THREE.PlaneGeometry(2.8,2.8);geometry.setAttribute('uv1',geometry.getAttribute('uv').clone());const mesh=new THREE.Mesh(geometry);scene.add(mesh);
const loader=new THREE.TextureLoader();let current=null,flat=null,pom=null,dbgH=null,dbgN=null,dbgA=null,width=2,height=2,localAssets=[];
function fail(e){const t=e?.message||String(e);state.errors.push(t);status.dataset.state='error';status.textContent='Ошибка: '+t;console.error(e)}
function tune(t,srgb=false){t.colorSpace=srgb?THREE.SRGBColorSpace:THREE.NoColorSpace;t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=true;return t}
function loadTex(url,srgb=false){return new Promise((res,rej)=>loader.load(url,t=>res(tune(t,srgb)),undefined,rej))}
function solid(r,g,b){const t=new THREE.DataTexture(new Uint8Array([r,g,b,255]),1,1,THREE.RGBAFormat);t.needsUpdate=true;return t}
const black=solid(0,0,0);
function dispose(){for(const m of[flat,pom,dbgH,dbgN,dbgA])m?.dispose?.();if(current?.owned)for(const t of Object.values(current.maps))t?.dispose?.()}
function params(){return{heightScale:+$('height').value,neutralLevel:+$('neutral').value,raiseScale:+$('raise').value,sinkScale:+$('sink').value,wallSoftnessPx:1,minSteps:+$('minSteps').value,maxSteps:+$('maxSteps').value,refinementSteps:+$('refine').value,maxUvOffset:.28,grazingFadeStart:.08,grazingFadeEnd:.22,jitterStrength:0,stableGradients:true}}
function outputs(){const p=params();$('heightOut').textContent=p.heightScale.toFixed(3);$('neutralOut').textContent=p.neutralLevel.toFixed(2);$('raiseOut').textContent=p.raiseScale.toFixed(2);$('sinkOut').textContent=p.sinkScale.toFixed(2);$('minOut').textContent=p.minSteps;$('maxOut').textContent=p.maxSteps;$('refineOut').textContent=p.refinementSteps;$('azOut').textContent=$('az').value+'°';$('elOut').textContent=$('el').value+'°'}
function pbr(isPom){const m=createPbrDecalMaterial({tint:'#ffffff'},{baseColor:current.maps.base,normal:current.maps.normal,orm:current.maps.orm,emissive:black});m.side=THREE.DoubleSide;m.roughness=.8;m.metalness=.15;m.aoMapIntensity=.6;if(isPom)enablePomDecalMaterial(m,{heightMap:current.maps.height,...params()});return m}
function rebuild(){for(const m of[flat,pom,dbgH,dbgN,dbgA])m?.dispose?.();flat=pbr(false);pom=pbr(true);dbgH=new THREE.MeshBasicMaterial({map:current.maps.height,toneMapped:false,side:THREE.DoubleSide});dbgN=new THREE.MeshBasicMaterial({map:current.maps.normal,toneMapped:false,side:THREE.DoubleSide});dbgA=new THREE.MeshBasicMaterial({map:current.maps.alpha,toneMapped:false,side:THREE.DoubleSide});apply();display()}
function apply(){outputs();if(pom)updatePomDecalMaterial(pom,params());render()}
function display(){if(!current)return;const cut=$('cutout').checked,mode=$('mode').value;for(const m of[flat,pom]){m.alphaMap=cut?current.maps.alpha:null;m.alphaTest=cut ? 0.05 : 0;m.transparent=cut;m.needsUpdate=true}render()}
async function loadProduction(id,meta){const r='./reference-pom-production/'+id+'/';const [base,heightT,normal,alpha,orm]=await Promise.all([loadTex(r+'basecolor.png',true),loadTex(r+'height.png'),loadTex(r+'normal.png'),loadTex(r+'alpha.png'),loadTex(r+'orm.png')]);return{maps:{base,height:heightT,normal,alpha,orm},w:meta.width,h:meta.height,owned:true,source:'production PNG'}}
function imageFile(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('Не удалось открыть '+file.name))};im.src=u})}
function rgbaTex(bytes,w,h,srgb=false){const t=new THREE.DataTexture(bytes,w,h,THREE.RGBAFormat);t.flipY=false;t.needsUpdate=true;return tune(t,srgb)}
async function buildLocal(file){const im=await imageFile(file),w=im.naturalWidth,h=im.naturalHeight,c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0);const d=x.getImageData(0,0,w,h).data,rgba=new Uint8Array(d),a=new Uint8Array(w*h),seed=new Uint8Array(w*h);for(let i=0;i<w*h;i++){const o=i*4,r=d[o],g=d[o+1],b=d[o+2],aa=d[o+3];a[i]=aa;const l=(.2126*r+.7152*g+.0722*b)/255;let v=.08+.88*Math.pow(l,.82);if(r>g*1.25&&r>b*1.4&&r>120)v=Math.max(v,.68);if(l<.16)v=Math.min(v,.20);seed[i]=Math.round(THREE.MathUtils.clamp(v,0,1)*255)}const p=params(),prep=preparePomReliefMaps(seed,w,h,p,a),hd=new Uint8Array(w*h*4),nd=new Uint8Array(w*h*4),ad=new Uint8Array(w*h*4),od=new Uint8Array(w*h*4);for(let i=0;i<w*h;i++){const o=i*4,H=Math.round(prep.heightField[i]*255);hd[o]=hd[o+1]=hd[o+2]=H;hd[o+3]=a[i];nd[o]=prep.normal[i*3];nd[o+1]=prep.normal[i*3+1];nd[o+2]=prep.normal[i*3+2];nd[o+3]=a[i];ad[o]=ad[o+1]=ad[o+2]=ad[o+3]=a[i];od[o]=255;od[o+1]=145;od[o+2]=26;od[o+3]=255}return{maps:{base:rgbaTex(rgba,w,h,true),height:rgbaTex(hd,w,h),normal:rgbaTex(nd,w,h),alpha:rgbaTex(ad,w,h),orm:rgbaTex(od,w,h)},w,h,owned:true,source:'local original '+file.name}}
async function select(id){status.dataset.state='';status.textContent='Загрузка '+id.toUpperCase()+'…';dispose();const meta=state.manifest?.find(x=>x.id===id);if(meta)try{current=await loadProduction(id,meta)}catch(e){const loc=localAssets.find(x=>x.id===id);if(!loc)throw e;current=await buildLocal(loc.file)}else{const loc=localAssets.find(x=>x.id===id);if(!loc)throw new Error('Нет production asset и локального оригинала для '+id);current=await buildLocal(loc.file)}$('selected').textContent=id.toUpperCase();$('resolution').textContent=current.w+'×'+current.h;$('source').textContent=current.source;const aspect=current.w/current.h;mesh.scale.set(aspect>=1?2.5:2.5*aspect,aspect>=1?2.5/aspect:2.5,1);rebuild();state.ready=true;state.source=current.source;status.dataset.state='ready';status.textContent='Готово · '+id.toUpperCase()+' · '+current.w+'×'+current.h+' · '+current.source}
function resize(){const b=$('view').getBoundingClientRect();width=Math.max(2,b.width|0);height=Math.max(2,b.height|0);renderer.setSize(width,height,false);camera.aspect=Math.floor(width/2)/height;camera.updateProjectionMatrix()}
function preset(k){const dist=Math.max(4.1,1.6/(Math.tan(THREE.MathUtils.degToRad(21))*camera.aspect)),d=k==='grazing'?new THREE.Vector3(.96,.06,.28):k==='oblique'?new THREE.Vector3(.55,.17,1):new THREE.Vector3(0,0,1);camera.position.copy(d.normalize().multiplyScalar(dist));controls.target.set(0,0,0);controls.update()}
function light(){const a=THREE.MathUtils.degToRad(+$('az').value),e=THREE.MathUtils.degToRad(+$('el').value);key.position.set(Math.cos(e)*Math.sin(a)*5,Math.sin(e)*5,Math.cos(e)*Math.cos(a)*5);outputs()}
function render(){if(!current)return;const s=Math.floor(width/2),mode=$('mode').value;let l=flat,r=pom;if(mode==='height')l=r=dbgH;else if(mode==='normal')l=r=dbgN;else if(mode==='alpha')l=r=dbgA;renderer.setScissorTest(true);mesh.material=l;renderer.setViewport(0,0,s,height);renderer.setScissor(0,0,s,height);renderer.render(scene,camera);mesh.material=r;renderer.setViewport(s,0,width-s,height);renderer.setScissor(s,0,width-s,height);renderer.render(scene,camera);renderer.setScissorTest(false);state.renderCount++}
async function init(){try{const r=await fetch('./reference-pom-production/manifest.json',{cache:'no-store'});if(r.ok){const j=await r.json();state.manifest=j.assets||[];for(const a of state.manifest){const o=new Option(a.id.toUpperCase(),a.id);$('decal').add(o)}await select(state.manifest[0].id)}else throw new Error('production pack пока не опубликован')}catch(e){fail(new Error('Не удалось загрузить production POM pack: '+(e?.message||String(e))))} }
const localFilesInput=$('localFiles');if(localFilesInput)localFilesInput.onchange=async e=>{localAssets=[...e.target.files].slice(0,10).map((file,i)=>({id:'ref-'+String(i+1).padStart(2,'0'),file}));$('decal').innerHTML='';for(const a of localAssets)$('decal').add(new Option(a.id.toUpperCase()+' · '+a.file.name,a.id));if(localAssets.length)select(localAssets[0].id).catch(fail)};
$('decal').onchange=()=>select($('decal').value).catch(fail);for(const id of['height','neutral','raise','sink','minSteps','maxSteps','refine'])$(id).oninput=apply;$('mode').onchange=display;$('cutout').onchange=display;for(const id of['az','el'])$(id).oninput=()=>{light();render()};for(const id of['front','oblique','grazing'])$(id).onclick=()=>{preset(id);render()};$('reset').onclick=()=>{Object.assign($('height'),{value:.04});$('neutral').value=.5;$('raise').value=1;$('sink').value=1;$('minSteps').value=12;$('maxSteps').value=96;$('refine').value=6;preset('front');apply()};
new ResizeObserver(()=>{resize();render()}).observe($('view'));resize();preset('front');light();let frames=0,t=performance.now();(function loop(now){controls.update();render();frames++;if(now-t>800){$('fps').textContent=Math.round(frames*1000/(now-t));frames=0;t=now}requestAnimationFrame(loop)})(t);init();
